metadata = [
    "Headache",
    "Encephalopathy",
    "Stroke",
    "Seizure",
    "Weakness",
    "Cranial Neuropathy",
    "Peripheral Neuropathy",
    "Myopathy",
    "Movement Disorder",
    "Personality Change",
    "Depression",
    "Pregnancy",
    "Nausea/Vomiting/Vertigo"
    "Old Age",
    "Medication",
    "Medical Past",
    "Surgery",
    "Memory Loss",
    "Diarrhoea",
    "Visual Disturbance",
    "Sustance Abuse",
    "Nerve Palsy",
    "Dysphagia",
    "Weight",
    "Fatigue",
    "Unresponsiveness",
    "Laceration",
    "Cognition Decline",
    "Fever",
    "Family Record",
    "Vital Signs Anomaly",
    "Lymphadenopathy",
    "Candidiasis",
    "Neck Stiffness",
    "Blood Exam",
    "CSF Anomaly",
    "Hallucinations",
    "Pain",
    "Appetite",
    "Skin Disease",
    "Urinary Problem",
    "Numbness",
    "Coma",
    "Respiratory Problem",
    "Cerebral Oedema",
    "Professional History",
    "Weak Legs",
    "Cardiopathy",
    "Constipation",
    "Sexual Impotence",
    "Sense Loss",
    "Urinary Exam"
]

symptoms = {
    "Headache": ["Dolor de cabeza general", "Dolor de cabeza localizado", "Migraña"],
    "Encephalopathy": ["Encefalopatía"],
    "Stroke": ["Derrame cerebral", ],
    "Seizure": ["Convulsiones"],
    "Weakness": ["Hemiparesia", "Extincion de estimulos sensoriales", "Disartria"],
    "Cranial Neuropathy": ["Neuropatia craneal", "Pliegue nasolabial", "Papiledema", "Movimiento facial ralentizado"],
    "Peripheral Neuropathy": ["Neuropatia periferica", "Debilidad isolada"],
    "Myopathy": ["Miopatía"],
    "Movement Disorder": ["Signo de Babinski", "Hemiplejia", "Perdida o disminución de reflejos", "Capacidad nula o disminuida de movimiento", "Hiperreflexia", "Distonia", "Marcha inestable", "Problema de coordinación", "Dificultad para caminar", "Movimiento torpe"],
    "Personality Change": ["Cambios de humor", "Irritabilidad", "Agresividad"],
    "Depression": ["Depresión"],
    "Pregnancy": ["Embarazo"],
    "Nausea/Vomiting/Vertigo": ["Nausea", "Mareo", "Vomito", "Vertigo"],
    "Old Age": [],
    "Medication": [],
    "Medical Past": [],
    "Surgery": [],
    "Memory Loss": ["Perdida de memoria corto plazo", "Perdida de memoria largo plazo"],
    "Diarrhoea": ["Diarrea"],
    "Visual Disturbance": ["Reflejo corneal ausente", "Pupila fija y/o dilatada", "Movimientos extraoculares ausentes", "Diplopia", "Perdida de vision", "Anomalia en el campo visual", "Fotofobia", "Vision borrosa", "Deriva del pronador"],
    "Sustance Abuse": ["Alcoholismo", "Uso de drogas", "Fumador"],
    "Nerve Palsy": ["Paralisis de nervio"],
    "Dysphagia": ["Disfagia"],
    "Weight": ["Perdida de peso", "Aumento de peso"],
    "Fatigue": ["Fatiga generalizada", "Somnolencia"],
    "Unresponsiveness": ["Falta de respuesta"],
    "Laceration": ["Herida", "Laceración"],
    "Cognition Decline": ["Letargo", "Desconocimiento de espacio, tiempo o persona", "Declive cognitivo", "Confusion", "Problemas para comunicarse", "Afasia"],
    "Fever": [],
    "Family Record": [],
    "Vital Signs Anomaly": [],
    "Lymphadenopathy": ["Linfadenopatia"],
    "Candidiasis": ["Candidiasis"],
    "Neck Stiffness": ["Rigidez de nuca"],
    "Blood Exam": [],
    "CSF Anomaly": [],
    "Hallucinations": ["Alucinaciones"],
    "Pain": ["Dolor general", "Dolor abdominal", "Dolor en extremidad/es"],
    "Appetite": ["Perdida de apetito", "Aumento de apetito"],
    "Skin Disease": ["Petequia"],
    "Urinary Problem": ["Incontinencia urinaria"],
    "Numbness": ["Entumecimiento", "Entumecimiento de extremidades"],
    "Coma": ["Coma"],
    "Respiratory Problem": ["Problemas respiratorios"],
    "Cerebral Oedema": ["Cerebral Oedema"],
    "Professional History": [],
    "Weak Legs": ["Piernas debiles"],
    "Cardiopathy": ["Cardiopatia"],
    "Constipation": ["Constipación"],
    "Sexual Impotence": ["Disfunción erectil"],
    "Sense Loss": ["Perdida o disminucion del gusto", "Perdida o disminucion del olfato", "Perdida o disminucion del oido"],
    "Urinary Exam": []
}

pure_symptoms = {
    "Headache": ["Dolor de cabeza general", "Dolor de cabeza localizado", "Migraña"],
    "Encephalopathy": ["Encefalopatía"],
    "Stroke": ["Derrame cerebral", ],
    "Seizure": ["Convulsiones"],
    "Weakness": ["Hemiparesia", "Extincion de estimulos sensoriales", "Disartria"],
    "Cranial Neuropathy": ["Neuropatia craneal", "Pliegue nasolabial", "Papiledema", "Movimiento facial ralentizado"],
    "Peripheral Neuropathy": ["Neuropatia periferica", "Debilidad isolada"],
    "Myopathy": ["Miopatía"],
    "Movement Disorder": ["Signo de Babinski", "Hemiplejia", "Perdida o disminución de reflejos", "Capacidad nula o disminuida de movimiento", "Hiperreflexia", "Distonia", "Marcha inestable", "Problema de coordinación", "Dificultad para caminar", "Movimiento torpe"],
    "Personality Change": ["Cambios de humor", "Irritabilidad", "Agresividad"],
    "Depression": ["Depresión"],
    "Pregnancy": ["Embarazo"],
    "Nausea/Vomiting/Vertigo": ["Nausea", "Mareo", "Vomito", "Vertigo"],
    "Memory Loss": ["Perdida de memoria corto plazo", "Perdida de memoria largo plazo"],
    "Diarrhoea": ["Diarrea"],
    "Visual Disturbance": ["Reflejo corneal ausente", "Pupila fija y/o dilatada", "Movimientos extraoculares ausentes", "Diplopia", "Perdida de vision", "Anomalia en el campo visual", "Fotofobia", "Vision borrosa", "Deriva del pronador"],
    "Sustance Abuse": ["Alcoholismo", "Uso de drogas", "Fumador"],
    "Nerve Palsy": ["Paralisis de nervio"],
    "Dysphagia": ["Disfagia"],
    "Weight": ["Perdida de peso", "Aumento de peso"],
    "Fatigue": ["Fatiga generalizada", "Somnolencia"],
    "Unresponsiveness": ["Falta de respuesta"],
    "Laceration": ["Herida", "Laceración"],
    "Cognition Decline": ["Letargo", "Desconocimiento de espacio, tiempo o persona", "Declive cognitivo", "Confusion", "Problemas para comunicarse", "Afasia"],
    "Lymphadenopathy": ["Linfadenopatia"],
    "Candidiasis": ["Candidiasis"],
    "Neck Stiffness": ["Rigidez de nuca"],
    "Hallucinations": ["Alucinaciones"],
    "Pain": ["Dolor general", "Dolor abdominal", "Dolor en extremidad/es"],
    "Appetite": ["Perdida de apetito", "Aumento de apetito"],
    "Skin Disease": ["Petequia"],
    "Urinary Problem": ["Incontinencia urinaria"],
    "Numbness": ["Entumecimiento", "Entumecimiento de extremidades"],
    "Coma": ["Coma"],
    "Respiratory Problem": ["Problemas respiratorios"],
    "Cerebral Oedema": ["Cerebral Oedema"],
    "Weak Legs": ["Piernas debiles"],
    "Cardiopathy": ["Cardiopatia"],
    "Constipation": ["Constipación"],
    "Sexual Impotence": ["Disfunción erectil"],
    "Sense Loss": ["Perdida o disminucion del gusto", "Perdida o disminucion del olfato", "Perdida o disminucion del oido"],
}