metadata = [
    "Headache",
    "Encephalopathy",
    "Stroke",
    "Seizure",
    "Weakness",
    "Cranial Neuropathy",
    "Peripheral Neuropathy",
    "Myopathy",
    "Movement Disorder",
    "Personality Change",
    "Depression",
    "Pregnancy",
    "Nausea/Vomiting/Vertigo"
    "Old Age",
    "Medication",
    "Medical Past",
    "Surgery",
    "Memory Loss",
    "Diarrhoea",
    "Visual Disturbance",
    "Sustance Abuse",
    "Nerve Palsy",
    "Dysphagia",
    "Weight",
    "Fatigue",
    "Unresponsiveness",
    "Laceration",
    "Cognition Decline",
    "Fever",
    "Family Record",
    "Vital Signs Anomaly",
    "Lymphadenopathy",
    "Candidiasis",
    "Neck Stiffness",
    "Blood Exam",
    "CSF Anomaly",
    "Hallucinations",
    "Pain",
    "Appetite",
    "Skin Disease",
    "Urinary Problem",
    "Numbness",
    "Coma",
    "Respiratory Problem",
    "Cerebral Oedema",
    "Professional History",
    "Weak Legs",
    "Cardiopathy",
    "Constipation",
    "Sexual Impotence",
    "Sense Loss",
    "Urinary Exam"
]